apiVersion: constraints.gatekeeper.sh/v1alpha1
kind:  {{ include "route.fullname" . | camelcase }}
metadata:
  name: {{ include "route.fullname" . | replace "-" "" }}-constraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: [ "Route" , "Pod"]
    namespaces: {{ .Values.namespaces }}
  parameters:
    ips: {{ include "route.ipValue" . | sortAlpha | join "," }}

