apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{(.Values.image).name |default "busybox"}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      name: budybox
      labels:
        app: busybox
    spec:
      containers:
        - name: {{(.Values.image).name |default "busybox"}}
          securityContext:
          image: {{(.Values.image).name |default "busybox"}}:{{(.Values.image).tag |default "latest"}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
