apiVersion: v1
kind: Service
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.port | default "8080"}}
      targetPort: {{.Values.targetPort | default "http"}}
      protocol: TCP
      name: http
  selector:
    app: busybox
